import pptxgen from "pptxgenjs";

const pptx = new pptxgen();
pptx.layout = "LAYOUT_WIDE"; // 13.333 x 7.5
pptx.author = "Samsung Customer Service";
pptx.company = "Samsung";
pptx.subject = "TCS/PQA Platform Introduction";
pptx.title = "Samsung TCS/PQA Formal Introduction";
pptx.lang = "en-US";

const C = {
  bg: "0A0A0A",
  panel: "141414",
  panel2: "1D1D1D",
  white: "FFFFFF",
  soft: "D9D9D9",
  muted: "AFAFAF",
  line: "3A3A3A",
};

function header(slide, title, subtitle = "") {
  slide.background = { color: C.bg };
  slide.addShape(pptx.ShapeType.rect, {
    x: 0,
    y: 0,
    w: 13.333,
    h: 0.7,
    fill: { color: "111111" },
    line: { color: "111111" },
  });

  slide.addText("SAMSUNG", {
    x: 0.45,
    y: 0.2,
    w: 2.6,
    h: 0.3,
    fontFace: "Aptos Display",
    fontSize: 20,
    bold: true,
    color: C.white,
    charSpace: 1.2,
  });

  slide.addText("TCS / PQA PERFORMANCE PLATFORM", {
    x: 8.0,
    y: 0.22,
    w: 4.9,
    h: 0.26,
    fontFace: "Aptos",
    fontSize: 10,
    bold: true,
    color: C.muted,
    align: "right",
    charSpace: 1,
  });

  slide.addText(title, {
    x: 0.7,
    y: 1.0,
    w: 12.0,
    h: 0.55,
    fontFace: "Aptos Display",
    fontSize: 32,
    bold: true,
    color: C.white,
  });

  if (subtitle) {
    slide.addText(subtitle, {
      x: 0.7,
      y: 1.58,
      w: 11.8,
      h: 0.35,
      fontFace: "Aptos",
      fontSize: 13,
      color: C.soft,
    });
  }
}

function panel(slide, x, y, w, h, title, body) {
  slide.addShape(pptx.ShapeType.roundRect, {
    x, y, w, h,
    rectRadius: 0.06,
    fill: { color: C.panel },
    line: { color: C.line, pt: 1 },
  });
  slide.addText(title, {
    x: x + 0.25,
    y: y + 0.18,
    w: w - 0.5,
    h: 0.26,
    fontFace: "Aptos",
    fontSize: 13,
    bold: true,
    color: C.white,
    charSpace: 0.6,
  });
  slide.addText(body, {
    x: x + 0.25,
    y: y + 0.52,
    w: w - 0.5,
    h: h - 0.7,
    fontFace: "Aptos",
    fontSize: 11,
    color: C.soft,
    breakLine: true,
    valign: "top",
  });
}

function bullets(items) {
  return items.map((t) => ({ text: `• ${t}`, options: { breakLine: true } }));
}

// Slide 1: Cover
{
  const s = pptx.addSlide();
  header(
    s,
    "Samsung TCS/PQA Platform",
    "Formal Introduction — Purpose, Workflow, Competition Culture, and Ranking Logic"
  );
  s.addShape(pptx.ShapeType.roundRect, {
    x: 0.9, y: 2.2, w: 11.5, h: 4.5,
    rectRadius: 0.08,
    fill: { color: C.panel2 },
    line: { color: C.line, pt: 1.2 },
  });
  s.addText(
    "A single digital platform to measure performance,\npublish transparent rankings, and support continuous engineer growth.",
    {
      x: 1.3, y: 3.1, w: 10.7, h: 2.2,
      fontFace: "Aptos Display",
      fontSize: 26,
      bold: true,
      align: "center",
      color: C.white,
      valign: "mid",
    }
  );
}

// Slide 2: Why this app exists
{
  const s = pptx.addSlide();
  header(s, "Why This App Exists", "The platform solves three business needs.");
  panel(
    s, 0.9, 2.1, 3.95, 4.5,
    "1) Unified Performance View",
    "Collects MX, DA, AV and PQA operational data in one place, reducing dependency on scattered files and manual tracking."
  );
  panel(
    s, 4.95, 2.1, 3.95, 4.5,
    "2) Fair & Clear Ranking",
    "Uses defined score logic and quarter scope so results are transparent, auditable, and trusted by management and engineers."
  );
  panel(
    s, 9.0, 2.1, 3.45, 4.5,
    "3) Fast Decisions",
    "Enables leadership to publish winners quickly and gives engineers immediate visibility into their KPI profile."
  );
}

// Slide 3: How app works
{
  const s = pptx.addSlide();
  header(s, "How The App Works", "End-to-end flow from data upload to dashboard publishing.");
  panel(
    s, 1.0, 2.15, 11.2, 1.1,
    "Step 1 — Data Upload",
    "Admin uploads product templates (MX / DA / AV / PQA)."
  );
  panel(
    s, 1.0, 3.4, 11.2, 1.1,
    "Step 2 — Mapping & Scoring",
    "System maps engineer code, ASC, SBA and computes score values per product logic."
  );
  panel(
    s, 1.0, 4.65, 11.2, 1.1,
    "Step 3 — Ranking & Winners",
    "Dashboard ranking is generated by product-quarter rules, with manual top-winner control when needed."
  );
  panel(
    s, 1.0, 5.9, 11.2, 0.75,
    "Step 4 — Engineer Search & Coaching",
    "Engineer searches by code and sees KPI details, score context, and performance direction."
  );
}

// Slide 4: Engineer perspective
{
  const s = pptx.addSlide();
  header(s, "Engineer Purpose In The App", "Every engineer uses the platform to understand performance, not only final rank.");
  panel(
    s, 0.9, 2.1, 5.7, 4.55,
    "What An Engineer Does",
    "1) Search by engineer code.\n2) Review personal KPI values and final score.\n3) Compare against required standards.\n4) Track monthly/quarterly progress.\n5) Focus improvement actions before next cycle."
  );
  panel(
    s, 6.85, 2.1, 5.5, 4.55,
    "What Management Gains",
    "• Standardized performance conversation.\n• Faster identification of strengths and gaps.\n• Objective reward and recognition cycle.\n• Better coaching plans by KPI evidence."
  );
}

// Slide 5: DA/AV criteria
{
  const s = pptx.addSlide();
  header(s, "DA / AV KPI Criteria", "In DA/AV engineer search, the criteria focus is aligned to uploaded template.");
  panel(
    s, 1.0, 2.2, 5.8, 4.3,
    "Displayed DA/AV Criteria",
    "• SSR\n• REDO\n• Chatbot\n• HASS\n• Acc Core Parts (VD)\n• Training Attendance\n• Linkage ratio"
  );
  panel(
    s, 7.05, 2.2, 5.25, 4.3,
    "Score Source",
    "Final Score is the main ranking score for DA/AV.\n\nEngineer code identifies the engineer.\nSBA ID is the display identity on profile/dashboard."
  );
}

// Slide 6: Competition objective
{
  const s = pptx.addSlide();
  header(s, "Main Target: Healthy Competition", "The platform is designed to create performance momentum.");
  panel(
    s, 0.9, 2.15, 11.45, 1.3,
    "Competition Principle",
    "Competition is based on transparent KPI evidence and clear score logic, not subjective judgment."
  );
  panel(
    s, 0.9, 3.65, 5.6, 3.0,
    "For Engineers",
    "• Know what to improve.\n• Compete with clear rules.\n• Track growth over time.\n• Earn recognition through measurable outcomes."
  );
  panel(
    s, 6.75, 3.65, 5.6, 3.0,
    "For Business",
    "• Raises service quality consistency.\n• Drives accountability.\n• Increases engagement through visible progress.\n• Supports data-driven talent decisions."
  );
}

// Slide 7: Ranking system
{
  const s = pptx.addSlide();
  header(s, "Ranking System", "How rankings and tiers are interpreted in the platform.");
  panel(
    s, 0.9, 2.1, 5.9, 4.5,
    "Ranking Mechanics",
    "• Rankings are calculated by product-specific score logic.\n• Quarter and year scope define the active ranking period.\n• Manual winners can set official top positions when required.\n• Engineer search profile explains the KPI background of each score."
  );
  panel(
    s, 7.0, 2.1, 5.4, 4.5,
    "Tier Framework (MX)",
    "Masters: 100–110\nDiamond: 90–99\nPlatinum: 80–89\nGold: 70–79\nSilver: 60–69\nBronze: below 60\n\nDA/AV ranking is driven by Final Score and winner configuration."
  );
}

// Slide 8: Governance
{
  const s = pptx.addSlide();
  header(s, "Governance & Reliability", "The platform is built to reduce ambiguity and improve trust.");
  s.addText(bullets([
    "Standard upload templates enforce consistent KPI structure.",
    "Product-specific parsing prevents cross-division mismatch.",
    "Manual winner controls allow leadership-aligned publishing.",
    "Engineer-code search gives traceable KPI evidence per person.",
    "Dashboard communication becomes faster and clearer."
  ]), {
    x: 1.0,
    y: 2.2,
    w: 11.5,
    h: 3.6,
    fontFace: "Aptos",
    fontSize: 17,
    color: C.soft,
    valign: "top",
  });
  s.addShape(pptx.ShapeType.line, { x: 1.0, y: 6.1, w: 11.3, h: 0, line: { color: C.line, pt: 1.2 } });
  s.addText("Result: One trusted performance language for engineers, operations, and leadership.", {
    x: 1.0, y: 6.25, w: 11.3, h: 0.45,
    fontFace: "Aptos Display",
    fontSize: 16,
    bold: true,
    color: C.white,
    align: "center",
  });
}

// Slide 9: Closing
{
  const s = pptx.addSlide();
  header(
    s,
    "Conclusion",
    "Samsung TCS/PQA platform operationalizes competition through transparent KPIs and clear ranking."
  );
  s.addShape(pptx.ShapeType.roundRect, {
    x: 1.05, y: 2.4, w: 11.2, h: 3.8,
    rectRadius: 0.08,
    fill: { color: C.panel2 },
    line: { color: C.line, pt: 1.2 },
  });
  s.addText(
    "Measure Fairly.\nCompete Clearly.\nImprove Continuously.",
    {
      x: 1.2, y: 3.0, w: 10.9, h: 2.4,
      fontFace: "Aptos Display",
      fontSize: 42,
      bold: true,
      color: C.white,
      align: "center",
      valign: "mid",
    }
  );
}

await pptx.writeFile({
  fileName: "Samsung_TCS_PQA_Formal_BW_Intro.pptx",
});

console.log("Created: Samsung_TCS_PQA_Formal_BW_Intro.pptx");
